- hosts: master.localdomain
  become: yes
  tasks:
    - name: initialize the cluster
      shell: |
        kubeadm init \
        --control-plane-endpoint=cluster.localdomain \
        --apiserver-advertise-address=MASTER_IP_ADDRESS \
        --pod-network-cidr=10.244.0.0/16 \
        --service-cidr=10.32.0.0/16 \
        --upload-certs >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: USERNAME
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
        
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/USERNAME/.kube/config
        remote_src: yes
        owner: USERNAME
        group: USERNAME

    - name: install Pod network
      become: yes
      become_user: USERNAME
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
